In [12]:
import numpy as np
# 1.1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
a = np.linspace(1,10, num = 10,dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# 1.2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
zero = np.zeros((3,3),dtype=int)
print(zero)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [27]:
# 1.3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
random_array_int = np.random.randint(1,11,(5,5))
print(random_array_int)

[[ 9  8  2  3  9]
 [ 8  4  9  8  6]
 [ 3  5  2  2  4]
 [ 9  9  1  5 10]
 [ 4  9  2  9  7]]


In [26]:
# 1.4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
random_array = np.random.random((4,4))
print(random_array)

[[0.96808722 0.77446714 0.8087865  0.07793842]
 [0.9002254  0.61353904 0.28818644 0.21649839]
 [0.29540011 0.65702047 0.09505827 0.06949004]
 [0.98255424 0.93827359 0.69768229 0.73657493]]


In [30]:
# 1.5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
x = np.random.randint(1,11,5)
y = np.random.randint(1,11,5)
total = x + y
diff = x - y
mult = x * y
print(f"Х: {x}")
print(f"Y: {y}")
print(f"Сума: {total}")
print(f"Різниця: {diff}")
print(f"Добуток: {mult}")

Х: [7 2 5 5 6]
Y: [1 5 4 4 7]
Сума: [ 8  7  9  9 13]
Різниця: [ 6 -3  1  1 -1]
Добуток: [ 7 10 20 20 42]


In [31]:
# 1.6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
ab = np.array([10,15,185,11,52,78,96],dtype = int)
bc = np.array([25,45,95,56,88,989,59],dtype = int)

scalyr = np.dot(ab,bc)
print(scalyr)

106498


In [32]:
# 1.7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
array_2x2 = np.random.randint(1,11,(2,2))
array_2x3 = np.random.randint(1,11,(2,3))
mul = np.dot(array_2x2,array_2x3)

print(f"Масив 2х2: {array_2x2}")
print(f"Масив 2х3: {array_2x3}")
print(f"Добуток:{mul}")

Масив 2х2: [[3 1]
 [2 2]]
Масив 2х3: [[4 7 1]
 [5 1 5]]
Добуток:[[17 22  8]
 [18 16 12]]


In [33]:
# 1.8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matrix_3x3 = np.random.randint(1,11,(3,3))
inv_matrix_3x3 = np.linalg.inv(matrix_3x3)
print(matrix_3x3)
print(inv_matrix_3x3)

[[10  2  5]
 [ 8  2  9]
 [ 5  7  4]]
[[ 0.18707483 -0.09183673 -0.02721088]
 [-0.04421769 -0.05102041  0.17006803]
 [-0.15646259  0.20408163 -0.01360544]]


In [34]:
# 1.9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix_4x4 = np.random.randint(1,11,(4,4))
transp_matrix_4x4 = matrix_4x4.T
print(matrix_4x4)
print(transp_matrix_4x4)

[[ 3  2  8 10]
 [ 1  3  7  4]
 [10 10  1  3]
 [ 4  4  7 10]]
[[ 3  1 10  4]
 [ 2  3 10  4]
 [ 8  7  1  7]
 [10  4  3 10]]


In [47]:
# 1.10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matrix_3x4 = np.random.randint(1,11,(3,4))
vector_4 = np.random.randint(1,11,4)
mul = np.dot(matrix_3x4,vector_4)
print(matrix_3x4)
print(vector_4)
print(mul)

[[8 8 3 6]
 [4 8 5 9]
 [2 5 2 3]]
[2 9 2 5]
[124 135  68]


In [52]:
# 1.11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
matrix_2x3 = np.random.random((2,3))
vector_3 = np.random.random(3)
mul = np.dot(matrix_2x3,vector_3)
print(matrix_2x3)
print(vector_3)
print(mul)

[[0.96864477 0.55025304 0.44218557]
 [0.78380511 0.58735537 0.97519009]]
[0.32151905 0.54725076 0.75463911]
[0.94625466 1.30935553]


In [54]:
# 1.12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
first_matrix_2x2 = np.random.randint(1,11,(2,2))
second_matrix_2x2 = np.random.randint(1,11,(2,2))
multply = first_matrix_2x2 * second_matrix_2x2
print(first_matrix_2x2)
print(second_matrix_2x2)
print(multply)

[[1 8]
 [4 8]]
[[10  2]
 [ 7  4]]
[[10 16]
 [28 32]]


In [55]:
# 1.13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
first_matrix_2x2_1 = np.random.randint(1,11,(2,2))
second_matrix_2x2_2 = np.random.randint(1,11,(2,2))
multply = np.dot(first_matrix_2x2_1,second_matrix_2x2_2)
print(first_matrix_2x2_1)
print(second_matrix_2x2_2)
print(multply)

[[10  7]
 [ 3  4]]
[[ 9 10]
 [ 7  2]]
[[139 114]
 [ 55  38]]


In [60]:
# 1.14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matrix_5x5 = np.random.randint(1,101,(5,5))
total_matrix = matrix_5x5.sum()
print(matrix_5x5)
print(total_matrix)

[[ 42  98  48  84  66]
 [100   6  96  41  20]
 [ 54  79   1  62  47]
 [ 61   5  68  75  43]
 [ 19   8   2  61  87]]
1273


In [59]:
# 1.15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix_4x4_1 = np.random.randint(1,11,(4,4))
matrix_4x4_2 = np.random.randint(1,11,(4,4))
diff = matrix_4x4_1 - matrix_4x4_2
print(matrix_4x4_1)
print(matrix_4x4_2)
print(diff)

[[6 5 3 8]
 [5 4 6 8]
 [7 7 1 9]
 [8 5 4 7]]
[[ 7 10  7  8]
 [10  5  3  3]
 [10  4  1  7]
 [ 4  6  2  8]]
[[-1 -5 -4  0]
 [-5 -1  3  5]
 [-3  3  0  2]
 [ 4 -1  2 -1]]


In [67]:
# 1.16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix_3x3 = np.random.random((3,3))
vector = np.array([matrix_3x3[0,:3].sum(),matrix_3x3[1,:3].sum(),matrix_3x3[2,:3].sum()])
print(matrix_3x3)
print(vector)

[[0.99590156 0.54141563 0.33131991]
 [0.13891123 0.08449842 0.79925165]
 [0.98070179 0.08373334 0.44966956]]
[1.8686371  1.0226613  1.51410469]


In [72]:
# 1.17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix_3x4 = np.array([[10,5,9,8],
                       [11,7,6,3],
                       [2,52,7,4]],dtype = int)

squad_matrix = matrix_3x4**2

print(squad_matrix)

[[ 100   25   81   64]
 [ 121   49   36    9]
 [   4 2704   49   16]]


In [74]:
# 1.18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
vector = np.random.randint(1,51,4)
sqrt_vector = vector ** (1/2)
print(vector)
print(sqrt_vector)

[42 37  4 29]
[6.4807407  6.08276253 2.         5.38516481]


In [75]:
# 2.1 Замініть усі непарні числа в arr на -1 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in range(len(arr)):
    if arr[i] % 2 != 0:
        arr[i] = -1

print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [83]:
# 2.2 Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками
d1_arr = np.array([1,2,3,4,5,6],dtype = int)
d2_arr = d1_arr.reshape((2,3))
print(d2_arr)



[[1 2 3]
 [4 5 6]]


In [85]:
# 2.3 Створіть два двовимірні масиви а і b, та складіть масиви їх вертикально
a = np.array([[1,2],
              [3,4]],dtype = int)
b = np.array([[5,6],
              [7,8]],dtype = int)
new_arr = np.vstack((a,b))
print(new_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [94]:
# 2.4 Створіть наступний шаблон без жорсткого кодування(Hard coding) . Використовуйте лише функції Numpy і наведений нижче масив введення Input:a = np.array([1,2,3])
# Output:array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])
first_part = np.repeat(a,3)
last_part = np.tile(a,3)
result = np.concatenate((first_part,last_part))
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [ ]:
# 2.5 Отримайте спільні елементи між a і b
# a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common_elements = np.intersect1d(a,b)
print(common_elements)

In [ ]:
# 2.6 Отримайте позиції перших 5 максимальних значень у заданому масиві a
# np.random.seed(100) a = np.random.uniform(1,50, 20)
np.random.seed(100)
a = np.random.uniform(1,50, 20)
sorted_index = np.argsort(a)[::-1]
result = sorted_index[:5]
print(a)
print(sorted_index)
print(result)


In [ ]:
# 2.7 Вилучіть усі значення NaN із одновимірного масиву
# а=np.array([1,2,3,np.nan,5,6,7,np.nan])
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a = np.array([el for el in a if not np.isnan(el)],dtype = int)
print(a)

In [ ]:
# 2.8 Обчисліть евклідову відстань між двома масивами a і b.
# a = np.array([1,2,3,4,5]) b = np.array([4,5,6,7,8]) 
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
c = a - b
c_square = c ** 2
total = np.sum(c_square)
result = np.sqrt(total)

print(c)
print(c_square)
print(total)
print(result)

In [ ]:
# 2.9 Знайдіть індекс 5-го повторення числа 1 у масиві x
# x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
indices = np.where(x == 1)[0]
fifth_index = indices[4]
print(fifth_index)

In [ ]:
# 2.10 Знайдіть повторювані записи (від 2-го випадку повторення і далі) у заданому масиві і позначте їх як True. Перше повторення має бути False.
# Input np.random.seed(100) a = np.random.randint(0, 5, 10)
# [0 0 3 0 2 4 2 2 2 2] Output [False True False True False False True True True True]

np.random.seed(100)
a = np.random.randint(0, 5, 10)
result = np.ones(len(a),dtype= bool)
_,first_indices  = np.unique(a,return_index=True)
result[first_indices] = False
print(result)